name: Reusable Shell Script Test

on:
  workflow_call:
    inputs:
      script-path:
        required: true
        type: string
      Environment:
        required: true
        type: string
      Environment11:
        required: true
        type: string
jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shell script
        run: bash ${{ inputs.script-path }}