name: Reusable Shell Script Test

on:
  workflow_call:
    inputs:
      script-path:
        required: true
        type: string
      MyEnvironment:
        required: true
        type: string
      # MyEnvironment11:
      #   required: true
      #   type: string
jobs:
  test-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Environment variables
        run: |
          echo "script-path=${{ inputs.script-path }}" >> "$GITHUB_ENV"
          echo "MyEnvironment=${{ inputs.MyEnvironment }}" >> "$GITHUB_ENV"
          echo "MyEnvironment11=${{ vars.MyEnvironment11 }}" >> "$GITHUB_ENV"
      - name: Run shell script
        run: bash ${{ inputs.script-path }}