name: Call Reusable Shell Script Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment2:
        description: 'Select the environment2 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment3:
        description: 'Select the environment3 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment4:
        description: 'Select the environment4 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment5:
        description: 'Select the environment5 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment6:
        description: 'Select the environment6 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment7:
        description: 'Select the environment7 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment8:
        description: 'Select the environment8 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment9:
        description: 'Select the environment9 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment10:
        description: 'Select the environment10 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      # Environment11:
      #   description: 'Select the environment11 to run the script'
      #   required: true
      #   default: dev
      #   options:
      #     - dev
      #     - staging
      #     - prod
      #   type: choice  

  # push:
    # branches: [main]
env:
  ENVIRONMENT11: prod2
  ENVIRONMENT12: prod3
  ENVIRONMENT13: prod4
  ENVIRONMENT14: prod5

jobs:
  EnvSetup:
    name: Setup Dynamic Environment Variables for reusable workflow
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment variables
        id: set-env-vars    
        run: |
          echo "ENVIRONMENT11=${{ ENVIRONMENT11 }}" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT12=${{ ENVIRONMENT12 }}" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT13=${{ ENVIRONMENT13 }}" >> "$GITHUB_OUTPUT"
          echo "ENVIRONMENT14=${{ ENVIRONMENT14 }}" >> "$GITHUB_OUTPUT"

  call-reusable:
    uses: ./.github/workflows/reusable-test.yml
    with:
      script-path: ./scripts/myscript.sh
      ENVIRONMENT: ${{ github.event.inputs.Environment }}
      ENVIRONMENT2: ${{ github.event.inputs.Environment2 }}
      ENVIRONMENT3: ${{ github.event.inputs.Environment3 }}
      ENVIRONMENT4: ${{ github.event.inputs.Environment4 }}
      ENVIRONMENT5: ${{ github.event.inputs.Environment5 }}
      ENVIRONMENT6: ${{ github.event.inputs.Environment6 }}
      ENVIRONMENT7: ${{ github.event.inputs.Environment7 }}
      ENVIRONMENT8: ${{ github.event.inputs.Environment8 }}
      ENVIRONMENT9: ${{ github.event.inputs.Environment9 }}
      ENVIRONMENT10: ${{ github.event.inputs.Environment10 }}
