name: Call Reusable Shell Script Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment2:
        description: 'Select the environment2 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment3:
        description: 'Select the environment3 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment4:
        description: 'Select the environment4 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment5:
        description: 'Select the environment5 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment6:
        description: 'Select the environment6 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment7:
        description: 'Select the environment7 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment8:
        description: 'Select the environment8 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment9:
        description: 'Select the environment9 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      Environment10:
        description: 'Select the environment10 to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice
      # Environment11:
      #   description: 'Select the environment11 to run the script'
      #   required: true
      #   default: dev
      #   options:
      #     - dev
      #     - staging
      #     - prod
      #   type: choice  

  # push:
    # branches: [main]
env:
  ENVIRONMENT11: prod2
  ENVIRONMENT12: prod3
  ENVIRONMENT13: prod4
  ENVIRONMENT14: prod5

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-test.yml
    with:
      script-path: ./scripts/myscript.sh
    