name: Call Reusable Shell Script Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        options:
          - dev
          - staging
          - prod
        type: choice

  # push:
    # branches: [main]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-test.yml
    with:
      script-path: ./scripts/myscript.sh